Hello World
===========

There are several versions of Hello World illustrating the fundamental ways of using Likely:

- **[hello_world.l](?show=library/hello_world.l)** - Run Likely as a Lisp interpreter
- **[hello_world_jit.c](share/likely/hello_world/hello_world_jit.c)** - Embed Likely as a just-in-time compiler
- **[hello_world_static.c](share/likely/hello_world/hello_world_static.c)** - Use Likely as a conventional static compiler
